before_install:
- npm i -g Laboratoria/mdlint

script: 
- npm run lint

notifications:
  webhooks: 
    urls:
      - http://skayo.lima-city.at/cpb/reportChecksFailure.php
    on_success: never
    on_failure: always
    on_start: never
